### PR TITLE
Made the story look nice.

### PR DESCRIPTION
**Pull request by XanderSuFromQBIX**

### CODE REVIEW

**Review by StickWolf — COMMENTED** [review]
no. when did you get assigned to change it?

**Review by Materia-xx — APPROVED** [review]

**Comment by XanderSuFromQBIX** [comment]
### _**I MADE IT LOOK NICE, I DID NOT CHANGE IT!!!!!**_

**Comment by StickWolf** [comment]
no.

**Comment by StickWolf** [comment]
_**That's my job, not yours**_

**Comment by XanderSuFromQBIX** [comment]
Yours was like

> Sentience.Sentience2
no spacees!!!

**Comment by StickWolf** [comment]
still no. never yes

**Comment by XanderSuFromQBIX** [comment]
I made it like,

> Sectience. Sectience2
Spaces!!

**Comment by StickWolf** [comment]
so? no. fix your spelling.

**Comment by StickWolf** [comment]
this is a long run on sentence. fix that

**Comment by StickWolf** [comment]
and get rid of the collin

**Comment by XanderSuFromQBIX** [comment]
No, sentences normaly contain that amount of words.

**Comment by XanderSuFromQBIX** [comment]
And to show what we are taking about, I put

> When the gems are merge d, it will the create an ancient weapon: The Moonrake
See?

**Comment by StickWolf** [comment]
I don't like the collin

**Comment by XanderSuFromQBIX** [comment]
So, we do not care if you  _**DON'T**_ like the collin!

**Comment by StickWolf** [comment]
don't care either

**Comment by XanderSuFromQBIX** [comment]
It is _**JUST**_a collin!

**Pull request closed without merging**
