### PR TITLE
Refactor the main "Play again" loop.

### PR DESCRIPTION
**Pull request by Materia-xx**
Rewrite the game play again loop a bit.

### CODE REVIEW

**Review by XanderSuFromQBIX — APPROVED** [review]
### I understand and approve you making the play again loop function better.
### THANK YOU.

**Review by StickWolf — COMMENTED** [review]
instead of having the game staring all over when the player dies, try making it so it goes to the last save. if there is no save yet, then the game stars all over. It'll be a bad idea to make it like,

> get as far as you can, oh no! I died! now I have to start all over again and this is the final boss!

**Comment by StickWolf** [comment]
was the final boss

**Review by XanderSuFromQBIX — DISMISSED** [review]

**Comment by Materia-xx** [comment]
Restarting the game from the last save is a great idea and I think we should do that. But currently the game doesn't even have a way to save yet. So maybe we can start with the code like this and rewrite it later when we have the save feature put in place. I'll write in a TODO comment so we remember to add this in.

**Comment by StickWolf** [comment]
just change the old TODO and make a new one

**Review by StickWolf — APPROVED** [review]
pretty good for now.

**Review by XanderSuFromQBIX — APPROVED** [review]
Look's nice, GOOD JOB!

**Pull request merged**
